### ISSUE TITLE
Split project into three separate repositories

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/ext#101]
We should have separate repositories: the client, the server, and the backend. Each of these repositories should have clearly documented interfaces so that the three components are not too tightly coupled.

**Comment by dalcde** [comment]
I think with what we have now, this is what we should do
 1. Move the cli binary back to the main crate. The original reason for separating was to make it more convenient to run `test`, but now with the python binding this is not as necessary.
 2. Move `ext-websocket` to a separate repository. I intend to continue maintaining this for now, but it need not be the "official" GUI interface now that we also have the python interface.

**Comment by hoodmane** [comment]
Sounds good. Go ahead and keep maintaining ext-websocket, at the very least it has the advantage that it runs in wasm. 

I'm planning to steal large amounts of code from ext-websocket in my rewrite. Once I'm done with that, we can discuss the design and work out any mistakes.

**Comment by dalcde** [comment]
Do you want to move the python bindings to a separate repository as
well? I feel like we will have to delve into the dark world of git
submodules.

**Comment by hoodmane** [comment]
I could go either way on the python bindings. You have an opinion? Having too much stuff in one repository is not very neat, so I guess I lean in favor of splitting.

We maybe could make an install repository that just has a script that clones all the other repositories and hooks them up. I guess this is just a poor man's version of git submodule though...

**Comment by dalcde** [comment]
On Fri, Mar 20, 2020 at 09:22:12PM -0700, Hood Chatham wrote:
>I could go either way on the python bindings. You have an opinion? Having too much stuff in one repository is not very neat, so I guess I lean in favor of splitting.

I think usually external language bindings are in separate repositories?

>We maybe could make an install repository that just has a script that clones all the other repositories and hooks them up. I guess this is just a poor man's version of git submodule though...

We can also just direct users to make a symlink

**Comment by hoodmane** [comment]
Do symlinks work the same on mac? I'm starting to worry about our mac users since everything is dependent on linux. For instance on mac you probably don't find python in `/usr/bin/pythonversion`. If you have a file that starts with `#!\bin\bash` will mac os run it correctly? I know that mac doesn't have `apt` for some reason. Maybe `brew` or some other package manager will work?

**Comment by dalcde** [comment]
On Fri, Mar 20, 2020 at 09:38:02PM -0700, Hood Chatham wrote:
>Do symlinks work the same on mac? I'm starting to worry about our mac users since everything is dependent on linux. For instance on mac you probably don't find python in `/usr/bin/pythonversion`. If you have a file that starts with `#!\bin\bash` will mac os run it correctly? I know that mac doesn't have `apt` for some reason. Maybe `brew` or some other package manager will work?

I think symlinks should be fine. I'm less sure about others.

**Comment by dalcde** [comment]
I think we should also separate steenrod_calculator
