### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/ext#104]
Many homotopy theorists use macs. Everything works well on linux, so also on Windows 10 via WSL. Certainly the situation is not as good on mac.

_Originally posted by @hoodmane in https://github.com/SpectralSequences/ext/issues/101#issuecomment-601993524_

**Comment by hoodmane** [comment]
Here we see that we can't assume that python is in `/usr/bin` on a mac (and they say in OSX >= 10.11.4 it is not possible to even make a symlink from `/usr/bin/python`. They can put python in `/usr/bin/local/python` but it is not the default installation location. SAD.

https://stackoverflow.com/questions/39928053/install-python-3-to-usr-bin-on-macos

**Comment by hoodmane** [comment]
We use virtualenv for everything though so the problem only occurs in a script that attempts to create the virtual environment.

**Comment by dalcde** [comment]
Wouldn't /usr/bin/env python3 work for everything?

**Comment by hoodmane** [comment]
That sounds like a good idea. I don't really know how this stuff works. Also, is there a way to post SpectralSequences global issues?

**Comment by dalcde** [comment]
Should we add macos travis tests?

**Comment by dalcde** [comment]
Travis now checks build on OS X as well.

**Comment by hoodmane** [comment]
Wow, cool!
