### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/ext#96]
Rust is fast, but it's pretty hard to write code in. Most of our users know how to use Python. An interpreter/console with full access to the backend is a key feature of useful software.

I want to make Python bindings and then rewrite the webserver in Python. Then we can provide a console window as part of the UI. The user can write arbitrary python code into this console window and it will be sent to the server and evaluated in the python environment the server is running in. 
I guess a simpler alternative would be to just drop into an interpreter in the console window after starting the webserver.

This way Users can add python code to run on start up installing extra callbacks, parsing different sorts of files, and significantly adjust the behavior of the application with much less effort than it takes to make even small modifications to the current Rust code base.

**Comment by hoodmane** [comment]
I think I'll prototype the design of this with a rewrite of js_spectralsequences in python.

**Comment by dalcde** [comment]
On Thu, Feb 13, 2020 at 04:54:44PM -0800, Hood Chatham wrote:
>I want to make Python bindings and then rewrite the webserver in Python. Then we can provide a console window as part of the UI.
I'm not sure if this is a good idea. Currently the webserver is one of
the big bottlenecks, but that can potentially be solved by writing a
better algorithm.

I agree with everything else.

**Comment by hoodmane** [comment]
What part of the webserver is the bottleneck? My guess is that we should be able to write rust bindings for the "hot path." We can pass around memory managed opaque pointers in Python. I think my biggest concern would be Python's limited threading capabilities.

For the record, Eric tells me that his (former) company had performance critical physics simulators that were written almost entirely in Lisp with some small amount of vector arithmetic in C. I think Lisp has better performance characteristics than Python, but it is also a garbage collected language.

I think the key thing is we need some way to modify and control the webserver using Python. 
[PyO3](https://github.com/PyO3/PyO3) has support for two way bindings, so it is possible that the correct design is for the Rust to be in charge of the Python runtime rather than the Python being in charge. It might be hard to attain the level of flexibility I would prefer in this way though.

**Comment by dalcde** [comment]
On 14 February 2020 11:28:02 GMT-05:00, Hood Chatham <notifications@github.com> wrote:
>What part of the webserver is the bottleneck? My guess is that we
>should be able to write rust bindings for the "hot path." We can pass
>around memory managed opaque pointers in Python. I think my biggest
>concern would be Python's limited threading capabilities.

Whenever we update a class, we need to recompute all structlines that involve the class, which is very slow and expensive.


>For the record, Eric tells me that his (former) company had performance
>critical physics simulators that were written almost entirely in Lisp
>with some small amount of vector arithmetic in C. I think Lisp has
>better performance characteristics than Python, but it is also a
>garbage collected language.
>
>I think the key thing is we need some way to modify and control the
>webserver using Python. 
>[PyO3](https://github.com/PyO3/PyO3) has support for two way bindings,
>so it is possible that the correct design is for the Rust to be in
>charge of the Python runtime rather than the Python being in charge. It
>might be hard to attain the level of flexibility I would prefer in this
>way though.
I think it is okay to let the python runtime be in charge because we wrap everything in Arc

**Comment by hoodmane** [comment]
> Whenever we update a class, we need to recompute all structlines that involve the class, which is very slow and expensive.

So we make a rust method called "recompute_structlines" that does that and then at least that expensive operation is improved and python can do the easy stuff.

**Comment by dalcde** [comment]
I'm also experimenting with python bindings at https://github.com/dalcde/rust_ext/tree/pyo3 . **WARNING** This branch is often rebased on top of master. Do not fork.

**Comment by hoodmane** [comment]
I will probably put my python bindings on another public github repository so we can compare them (currently I only have a local copy). I'm working my way up -- I have some decent bindings for FpVector and Matrix so now I'm working on the algebras.

**Comment by hoodmane** [comment]
This mostly works now by ccc3801deee552f5c45654f7fd78e7e457dbfd35
